#!/bin/sh
# zig cc for x86_64-windows-gnu, dropping the MinGW linker flags FFmpeg's configure adds that zig's linker rejects.
args=""
for a in "$@"; do case "$a" in
  -Wl,--pic-executable*|-Wl,--image-base*|-Wl,--nxcompat*) ;;
  *) args="$args '$(printf %s "$a" | sed "s/'/'\\\\''/g")'";;
esac; done
eval exec zig cc -target x86_64-windows-gnu $args
